export const shippingLocations = {
  UY: [
    {
      code: "AR",
      name: "Artigas",
      cities: [
        "Ciudad de Artigas",
        "Bella Unión",
        "Baltasar Brum",
        "Bernabé Rivera",
        "Cainsa",
        "Cerro Ejido",
        "Colonia Palma",
        "Coronado",
        "Cuareím",
        "Cuaró",
        "Diego Lamas",
        "Javier de Viana",
        "Mones Quintela",
        "Paso Campamento",
        "Paso Farías",
        "Pintadito",
        "Rincón de Pacheco",
        "Sequeira",
        "Tomás Gomensoro",
        "Topador",
      ],
    },
    {
      code: "CA",
      name: "Canelones",
      cities: [
        "Atlántida",
        "Barros Blancos",
        "Ciudad de Canelones",
        "Ciudad de la Costa",
        "Colonia Nicolich",
        "Costa de Oro",
        "La Paz",
        "Las Piedras",
        "Los Cerrillos",
        "Pando",
        "Parque del Plata",
        "Progreso",
        "San Bautista",
        "San Jacinto",
        "San Ramón",
        "Santa Lucía",
        "Sauce",
        "Tala",
        "Toledo",
        "18 de Mayo",
        "Aguas Corrientes",
        "Araminda",
        "Balneario Argentino",
        "Barrio Remanso",
        "Bello Horizonte",
        "Biarritz",
        "Bolívar",
        "Campo Militar",
        "Canelón Chico",
        "Capilla de Cella",
        "Castellanos",
        "City Golf",
        "Costa Azul",
        "Cruz de los Caminos",
        "Cuchilla Alta",
        "El Dorado",
        "El Galeón",
        "Empalme Olmos",
        "Estación Atlántida",
        "Estación La Floresta",
        "Estación Migues",
        "Estación Pedrera",
        "Estanque de Pando",
        "Fortín de Santa Rosa",
        "Guazú-Virá",
        "Guazuvirá Nuevo",
        "Jardines de Pando",
        "Jaureguiberry",
        "Joaquín Suárez",
        "Juanicó",
        "La Floresta",
        "La Montañesa",
        "La Tuna",
        "Las Toscas",
        "Lomas de Carrasco",
        "Los Titanes",
        "Marindia",
        "Migues",
        "Montes",
        "Neptunia",
        "Olmos",
        "Parada Cabrera",
        "Parador Tajes",
        "Paso Carrasco",
        "Paso de la Cadena",
        "Paso de Pache",
        "Paso Espinosa",
        "Paso Palomeque",
        "Piedra del Toro",
        "Piedras de Afilar",
        "Pinamar",
        "Salinas",
        "San Antonio",
        "San Luis",
        "Santa Ana",
        "Santa Lucía del Este",
        "Santa Rosa",
        "Soca",
        "Tapia",
        "Totoral del Sauce",
        "Villa Aeroparque",
        "Villa Arejo",
        "Villa Argentina",
        "Villa Crespo y San Andrés",
        "Villa Foresti",
      ],
    },
    {
      code: "CL",
      name: "Cerro Largo",
      cities: [
        "Melo",
        "Río Branco",
        "Aceguá",
        "Arachania",
        "Arbolito",
        "Arévalo",
        "Bañado de Medina",
        "Centurión",
        "Cerro de las Cuentas",
        "Esperanza",
        "Fraile Muerto",
        "Getulio Vargas",
        "Isidoro Noblía",
        "La Pedrera",
        "Lago Merín",
        "Las Cañas",
        "Mangrullo",
        "Nando",
        "Ñangapiré",
        "Plácido Rosas",
        "Quebracho",
        "Ramón Trigo",
        "Soto Goro",
        "Toledo",
        "Tres Islas",
        "Tupambaé",
        "Uruguay",
      ],
    },
    {
      code: "CO",
      name: "Colonia",
      cities: [
        "Carmelo",
        "Colonia del Sacramento",
        "Conchillas",
        "Juan Lacaze",
        "Nueva Helvecia",
        "Nueva Palmira",
        "Rosario",
        "Tarariras",
        "Agraciada",
        "Arrivillaga",
        "Artilleros",
        "Barker",
        "Blancarena",
        "Boca del Rosario",
        "Brisas del Plata",
        "Britópolis",
        "Campana",
        "Cerro de las Armas",
        "Chico Torino",
        "Colonia Cosmopolita",
        "Colonia Valdense",
        "Cufré",
        "El Ensueño",
        "El Semillero",
        "Estanzuela",
        "Florencio Sánchez",
        "Fomento",
        "Gil",
        "Juan Carlos Caseros",
        "Juan Jackson",
        "La Horqueta",
        "La Paz",
        "Laguna de los Patos",
        "Las Víboras",
        "Los Cerros de San Juan",
        "Los Pinos",
        "Mevir San Pedro",
        "Miguelete",
        "Minuano",
        "Montes del Plata",
        "Ombúes de Lavalle",
        "Paso Antolín",
        "Playa Azul",
        "Playa Parant",
        "Puerto Inglés",
        "Radial Conchillas",
        "Riachuelo",
        "Santa Ana",
        "Santa Regina",
        "Zagarzazú",
      ],
    },
    {
      code: "DU",
      name: "Durazno",
      cities: [
        "Cerro Chato",
        "Ciudad de Durazno",
        "Sarandí del Yi",
        "Aguas Buenas",
        "Baygorria",
        "Blanquillo",
        "Carlos Reyles",
        "Centenario",
        "Colonia Rossell y Rius",
        "Cuchilla de Ramírez",
        "Feliciano",
        "La Paloma",
        "San Jorge",
        "Santa Bernardina",
        "Villa del Carmen",
      ],
    },
    {
      code: "FS",
      name: "Flores",
      cities: [
        "Trinidad",
        "Andresito",
        "Cerro Colorado",
        "Chamangá",
        "Ismael Cortinas",
        "Juan José Castro",
        "La Casilla",
      ],
    },
    {
      code: "FD",
      name: "Florida",
      cities: [
        "Cerro Chato",
        "Ciudad de Florida",
        "Sarandí Grande",
        "Veinticinco de Agosto",
        "25 de Mayo",
        "Alejandro Gallinal",
        "Berrondo",
        "Capilla del Sauce",
        "Cardal",
        "Casupá",
        "Chamizo",
        "Estación Capilla del Sauce",
        "Fray Marcos",
        "Goñi",
        "Illescas",
        "Independencia",
        "La Cruz",
        "Mendoza",
        "Mendoza Chico",
        "Montecoral",
        "Nico Pérez",
        "Polanco del Yi",
        "Pueblo Barceló",
        "Puntas de Maciel",
        "Reboledo",
        "San Gabriel",
        "Valentines",
      ],
    },
    {
      code: "LA",
      name: "Lavalleja",
      cities: [
        "José Pedro Varela",
        "Minas",
        "Aguas Blancas",
        "Aramendía",
        "Blanes Viale",
        "Colón",
        "Diecinueve de Junio",
        "Estación Solís",
        "Gaetán",
        "Illescas",
        "José Batlle y Ordóñez",
        "Mariscala",
        "Pirarajá",
        "Polanco Norte",
        "San Francisco de las Sierras",
        "Solís de Mataojo",
        "Villa del Rosario",
        "Villa Serrana",
        "Zapicán",
      ],
    },
    {
      code: "MA",
      name: "Maldonado",
      cities: [
        "Aiguá",
        "Ciudad de Maldonado",
        "La Barra",
        "Piriápolis",
        "Punta del Este",
        "San Carlos",
        "Arenas de José Ignacio",
        "Balneario Buenos Aires",
        "Bella Vista",
        "Cerros Azules",
        "Chihuahua",
        "Cumbres de la Ballena",
        "Edén Rock",
        "El Chorro",
        "El Edén",
        "El Tesoro",
        "Estación Las Flores",
        "Garzón",
        "Gerona",
        "Gregorio Aznárez",
        "José Ignacio",
        "La Capuera",
        "Las Flores",
        "Los Talas",
        "Manantiales",
        "Nueva Carrara",
        "Ocean Park",
        "Pan de Azúcar",
        "Playa Grande",
        "Playa Hermosa",
        "Playa Verde",
        "Portezuelo",
        "Pueblo Solís",
        "Punta Ballena",
        "Punta Colorada",
        "San Vicente",
        "Santa Mónica",
        "Sauce de Portezuelo",
        "Solís",
      ],
    },
    {
      code: "MO",
      name: "Montevideo",
      cities: ["Montevideo", "Santiago Vázquez"],
    },
    {
      code: "PA",
      name: "Paysandú",
      cities: [
        "Ciudad de Paysandú",
        "Alonso",
        "Araújo",
        "Arbolito",
        "Beisso",
        "Bella Vista",
        "Campamento de Purificación",
        "Cañada del Pueblo",
        "Casa Blanca",
        "Cerro Chato",
        "Chapicuy",
        "Constancia",
        "Cuchilla de Buricayupí",
        "Cuchilla de Fuego",
        "El Eucalipto",
        "Esperanza",
        "Estación Porvenir",
        "Federación",
        "Gallinal",
        "Guichón",
        "La Tentación",
        "Lorenzo Geyres",
        "Merinos",
        "Morató",
        "Orgoroso",
        "Piedra Sola",
        "Piedras Coloradas",
        "Piñera",
        "Porvenir",
        "Puntas de Arroyo Negro",
        "Quebracho",
        "Queguayar",
        "Soto",
        "Tambores",
        "Termas de Almirón",
        "Termas del Guaviyú",
        "Villa María",
        "Zeballos",
      ],
    },
    {
      code: "RN",
      name: "Río Negro",
      cities: [
        "Fray Bentos",
        "Nuevo Berlín",
        "Young",
        "Algorta",
        "Barrio Anglo",
        "Bellaco",
        "Colonia Ofir",
        "El Ombú",
        "Gartental",
        "Grecco",
        "Las Cañas",
        "Los Arrayanes",
        "Menafra",
        "Paso de los Mellizos",
        "San Javier",
        "Sarandí de Navarro",
        "Tres Quintas",
        "Villa General Borges",
        "Villa María",
      ],
    },
    {
      code: "RV",
      name: "Rivera",
      cities: [
        "Minas de Corrales",
        "Ciudad de Rivera",
        "Tranqueras",
        "Vichadero",
        "Amarillo",
        "Arroyo Blanco",
        "Cerrillada",
        "Cerro Pelado",
        "Cerros de la Calera",
        "La Puente",
        "Lagos del Norte",
        "Las Flores",
        "Masoller",
        "Moirones",
        "Paso Ataques",
        "Paso Hospital",
      ],
    },
    {
      code: "RO",
      name: "Rocha",
      cities: [
        "Chuy",
        "Ciudad de Rocha",
        "18 de Julio",
        "19 de Abril",
        "Aguas Dulces",
        "Arachania",
        "Barra de Valizas",
        "Barra del Chuy",
        "Cabo Polonio",
        "Castillos",
        "Cebollatí",
        "Chuy",
        "Costa Azul",
        "La Coronilla",
        "La Esmeralda",
        "La Paloma",
        "La Pedrera",
        "La Ribiera",
        "Lascano",
        "Oceanía del Polonio",
        "Palmares de la Coronilla",
        "Parallé",
        "Pueblo Nuevo",
        "Puerto de los Botes",
        "Puimayen",
        "Punta del Diablo",
        "Punta Rubia",
        "San Antonio",
        "San Luis al Medio",
        "Santa Isabel de la Pedrera",
        "Santa Teresa",
        "Tajamares de la Pedrera",
        "Velázquez",
      ],
    },
    {
      code: "SA",
      name: "Salto",
      cities: [
        "Ciudad de Salto",
        "Albisu",
        "Arenitas Blancas",
        "Arerunguá",
        "Belén",
        "Biassini",
        "Campo de Todos",
        "Cayetano",
        "Celeste",
        "Cerro de Vera",
        "Colonia 18 de Julio",
        "Colonia Itapebí",
        "Colonia Lavalleja",
        "Constitución",
        "Cuchilla de Guaviyú",
        "Fernández",
        "Garibaldi",
        "Guaviyú de Arapey",
        "Las Flores",
        "Laureles",
        "Lluveras",
        "Migliaro",
        "Olivera",
        "Palomas",
        "Paso Cementerio",
        "Paso del Parque del Daymán",
        "Puntas de Valentín",
        "Quintana",
        "Rincón de Valentín",
        "Russo",
        "San Antonio",
        "Sarandí del Arapey",
        "Saucedo",
        "Termas del Arapey",
        "Termas del Daymán",
      ],
    },
    {
      code: "SJ",
      name: "San José",
      cities: [
        "Ciudad del Plata",
        "Ecilda Paullier",
        "Libertad",
        "San José de Mayo",
        "18 de Julio-Pueblo Nuevo",
        "Arazatí",
        "Boca del Cufré",
        "Capurro",
        "Carreta Quemada",
        "Cerámicas del Sur",
        "Cololó",
        "Colonia Delta",
        "Colonia Wilson",
        "Costas de Pereira",
        "Fabre",
        "González",
        "Ituzaingó",
        "Juan Soler",
        "Kiyú",
        "La Boyada",
        "La Radial",
        "Mal Abrigo",
        "Mangrullo",
        "Puntas de Valdez",
        "Rafael Perazza",
        "Raigón",
        "Rincón del Pino",
        "Rodríguez",
        "San Gregorio de Carro",
        "Scavino",
        "Villa María",
      ],
    },
    {
      code: "SO",
      name: "Soriano",
      cities: [
        "Cardona",
        "Dolores",
        "Mercedes",
        "Agraciada",
        "Cañada Nieto",
        "Castillos",
        "Chacras de Dolores",
        "Colonia Concordia",
        "Cuchilla del Perdido",
        "Egaña",
        "El Tala",
        "José Enrique Rodó",
        "La Concordia",
        "Lares",
        "Palmar",
        "Palmitas",
        "Palo Solo",
        "Perseverano",
        "Risso",
        "Sacachispas",
        "Santa Catalina",
        "Villa Soriano",
      ],
    },
    {
      code: "TA",
      name: "Tacuarembó",
      cities: [
        "Ciudad de Tacuarembó",
        "Curtina",
        "Paso de los Toros",
        "San Gregorio de Polanco",
        "Achar",
        "Balneario Iporá",
        "Cardozo",
        "Chamberlain",
        "Clara",
        "Cuchilla de Caraguatá",
        "Cuchilla de Peralta",
        "Cuchilla del Ombú",
        "Curtina",
        "La Hilera",
        "La Pedrera",
        "Las Toscas",
        "Laureles",
        "Montevideo Chico",
        "Paso Bonilla",
        "Paso de los Novillos",
        "Paso del Cerro",
        "Piedra Sola",
        "Pueblo de Arriba",
        "Pueblo de Barro",
        "Punta de Carretera",
        "Puntas de Cinco Sauces",
        "Rincón de Pereira",
        "Rincón del Bonete",
        "Sauce de Batoví",
        "Tambores",
        "Valle Edén",
        "Villa Ansina",
      ],
    },
    {
      code: "TT",
      name: "Treinta y Tres",
      cities: [
        "Cerro Chato",
        "Ciudad de Treinta y Tres",
        "Alonso",
        "Arrocera Los Ceibos",
        "Arrocera Zapata",
        "Arrozal Treinta y Tres",
        "Costas del Tacuarí",
        "El Bellaco",
        "General Enrique Martínez",
        "Isla Patrulla",
        "María Albina",
        "Mendizábal",
        "Puntas del Parao",
        "Rincón",
        "Santa Clara de Olimar",
        "Valentines",
        "Vergara",
        "Villa Passano",
        "Villa Sara",
      ],
    },
  ],
};

export const documentTypes = {
  UY: [
    {
      code: 1,
      name: "RUT",
    },
    {
      code: 2,
      name: "Cédula de Identidad",
    },
    {
      code: 3,
      name: "Extranjero",
    },
  ],
};

// TODO: Pull from Admin Console DB
export const shippingMethods = {
  UY: [
    {
      name: "4-5 Días",
      price: "Grátis",
    },
    {
      name: "2-3 Días",
      price: 200,
    },
    {
      name: "Envío al día siguiente",
      price: 300,
    },
  ],
};
