import "./globals.css";
import { Nunito } from "next/font/google";
import Header from "src/components/Header";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Fake Store",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <main className={"flex flex-col h-full w-full"}>
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
